### ISSUE TITLE
Compatibility with latest Redmine version 4.0.x

### ISSUE THREAD

**Issue by deining** [batizhevsky/redmine_pretend#31]
The plugin does not work with the newly released Redmine version 4.0.x.
Would be great to have a fix here!
Any input is appreciated.

**Comment by onlyjob** [comment]
Apparently there is an actively maintained fork with Redmine 4 support:

  https://github.com/AlphaNodes/redmine_pretend/commits/master

@batizhevsky, perhaps you could work with @alexandermeindl to incorporate Redmine v4 support here?

IMHO it would benefit users of this plugin if developers cooperate around single authoritative repository. Note that fork have no issue tracker so it is only possible to report bugs here.

Thanks.

**Comment by hermannkm** [comment]
Not working on 4.2.x

```
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
```

**Comment by srghma** [comment]
https://github.com/AlphaNodes/redmine_pretend/commits/master was deleted

**Comment by marcelom87** [comment]
Hey Guys,
alphanodes stopped providing this plugin, anyone knows a candidate replacement for Redmine 4.x and beyond.

**Comment by batizhevsky** [comment]
Author here. The plugin is very old, unmaintained, and contains very bad code practices. I don't work with redmine for very long, I'll try to fix it, but can't promise. It's better find another solution to the problem

**Comment by marcelom87** [comment]
> Author here. The plugin is very old, unmaintained, and contains very bad code practices. I don't work with redmine for very long, I'll try to fix it, but can't promise. It's better find another solution to the problem

Dude you are amazing! Because your plugin is still the only one that makes this very useful function.
You have all my admiration!
