### ISSUE TITLE
doesn't work with 3.4

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [batizhevsky/redmine_pretend#27]
/srv/www/redmine/plugins/redmine_pretend/init.rb:3:in `<top (required)>': undefined method `to_prepare' for ActionDispatch::Callbacks:Class (NoMethodError)
Did you mean?  to_param
